name: self-driving-car-model
channels:
- https://conda.anaconda.org/menpo
- defaults
- conda-forge
- anaconda
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
    - moviepy
    - tensorflow-gpu
    - keras
    - pydot
    - graphviz
    - tensorboard
    - pip:
        - opencv-contrib-python
